# Generated by Django 5.0.6 on 2024-09-02 20:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CCTVFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cctv_name', models.CharField(max_length=255)),
                ('feed_url', models.CharField(max_length=255)),
                ('first_frame_image', models.ImageField(blank=True, null=True, upload_to='first_frames/')),
            ],
        ),
        migrations.CreateModel(
            name='CCTVFootages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('cctv_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.cctvfeed')),
            ],
        ),
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('museum_name', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ROI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roi_name', models.CharField(max_length=255)),
                ('coordinates', models.TextField()),
                ('cctv_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.cctvfeed')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('museum_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.museum')),
            ],
        ),
        migrations.CreateModel(
            name='DetectionResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_start', models.TimeField(default=django.utils.timezone.now)),
                ('time_end', models.TimeField(default=django.utils.timezone.now)),
                ('visitor_passing_count', models.IntegerField(default=0)),
                ('visitor_interested_count', models.IntegerField(default=0)),
                ('roi_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.roi')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='museum.room')),
            ],
        ),
        migrations.AddField(
            model_name='cctvfeed',
            name='room_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.room'),
        ),
    ]
